### ISSUE TITLE
Release new version of egui-wgpu to crates.io with wgpu 0.13 support

### ISSUE THREAD

**Issue by kaphula** [emilk/egui#1839] opened 2022-07-17 23:52 UTC
Or better yet, with wgpu 0.13.1 support. Currently the [latest version](https://crates.io/crates/egui_wgpu) uses wgpu 0.12 even though 0.13 [seems to be in use](https://github.com/emilk/egui/blob/master/egui-wgpu/Cargo.toml#L43) inside this repository?

**Comment by samoylovfp** [comment] 2022-07-18 10:36
I was playing around with wgpu version of `eframe` from the main branch of this repo and having lots of fun.
Got thinking the same thing.
Is there a pre-release checklist?
Maybe we could help with some chores

**Comment by emilk** [comment] 2022-07-21 18:00
The problem is that `egui-wgpu` on `master` is incompatible with latest egui (`0.18`) (at least if I recall correctly), which means we also need to do a new egui release first.

The alternative is to make a branch with a `egui-wgpu` for `egui=0.18` and do a release off that, but that's a bit of work to do.

**Comment by emilk** [comment] 2022-07-21 18:17
Duplicate of https://github.com/emilk/egui/issues/1805

**Closed by emilk** 2022-07-21 18:17 UTC
