### ISSUE TITLE
[Linux] Frequent crashes when starting application, X-related

### ISSUE THREAD

**Issue by the-drunk-coder** [emilk/egui#446] opened 2021-05-28 16:21 UTC
Hi,

recently I'm having plenty of (non-deterministic) crashes when starting my egui-based application.

```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
megra_rs: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

Not really sure what this means. Usually I have to try two or three times, then the application starts. Any hints ?

I'm on Arch, Xorg, AwesomeWM

Best,
N

**Comment by slve** [comment] 2021-06-02 11:24
I see get the same message, not just frequently, but any time I try to use the lib through epick.
Arch, xorg, dwm here.

**Comment by jhimcras** [comment] 2021-06-02 16:12
I've got exactly same error message above.
I'm on Arch, i3wm

**Comment by the-drunk-coder** [comment] 2021-06-02 19:10
There was something in the underlying winit library, supposedly fixed: 

https://github.com/rust-windowing/winit/issues/458

**Comment by d4h0** [comment] 2021-07-04 13:01
I get this error as well (also on Arch Linux with i3, running the egui_template or the demo app).

Does anybody know how to overcome this?

The web backend works, fortunately, but it would be nice to run apps without a browser and the limitations of WASM.

**Comment by d4h0** [comment] 2021-07-04 18:55
Because this was tagged with `egui_glium` I tried to run [glium's examples](https://github.com/rust-windowing/glutin/tree/master/glutin_examples/examples). 80% percent fail with the same error that everybody here gets (the other 20% fail in different ways).

I cloned `egui_template` again, and tried to execute the example without modifying the code in any way. The app opened once, but not again after.

**Comment by AZMCode** [comment] 2021-09-25 20:17
I have the same issue on every start, deterministically. Currently running Gentoo and available for further debugging.

**Comment by emilk** [comment] 2021-09-26 01:12
Similar issue, reported closed: https://github.com/rust-windowing/winit/issues/458

> Because this was tagged with `egui_glium` I tried to run [glium's examples](https://github.com/rust-windowing/glutin/tree/master/glutin_examples/examples). 80% percent fail with the same error that everybody here gets (the other 20% fail in different ways).

Let's  figure out if this is a problem with glium or winit. There is a new glium-free backend in the works at https://github.com/emilk/egui/pull/685 - can you check it out and try to run it?

> I cloned `egui_template` again, and tried to execute the example without modifying the code in any way. The app opened once, but not again after.

try removing the state at `/home/UserName/.local/share/egui_template` - does it work now? If so, see if you can figure out what part of the config file is causing the problem (maybe restoring the position or the size of the window?)

**Comment by AZMCode** [comment] 2021-09-26 12:24
Just ran the demo app without glium and it worked a charm. Running the demo app with glium, however, works as well. I'm baffled. Could it be there's an issue with eframe? The bug seems too low level to be, but I cannot repro on my side.

**Comment by AZMCode** [comment] 2021-09-27 17:45
Nevermind. Started doing dev on my side when the issue popped up again, and quickly switched my deps to the glow branch. Still got the issue. So it's not *only* glium.

**Comment by AZMCode** [comment] 2021-09-28 15:57
Since I'm running Gentoo after all I've been compiling a lot of stuff. And I don't know if this is a lead or not, but there seem to be less crashes when my computer is busy doing something.

**Comment by the-drunk-coder** [comment] 2021-12-24 12:26
> After some testing with the glium-free backend, it seems this is not a problem with glium. I'd advise to remove the egui_glium tag,

Yes, just tried with the glow backend, same problem.

**Comment by smorokin** [comment] 2022-02-02 14:21
I get also the same error message using the eframe_template on Kubuntu 21.10:
````
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
egui_test: ../../src/xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
````

**Comment by LongHairedHacker** [comment] 2022-02-03 11:27
I ran into the same `!xcb_xlib_threads_sequence_lost` assertion a few days ago.
For me any egui example I try to run crashes 100% of the time, so my system might be a good environment to reproduce this problem.

Since https://github.com/rust-windowing/glutin/issues/1034#issuecomment-1007958758 suggests that it might be window manager related, I'd like to add that I also use i3 (also on Arch Linux).

I did not yet test the glow backend, but I will give it a try if can free up some time later today.

If there is anything else I should give a try just point me at piece of code and I'll try it out.
Likewise if there is any additional information about my system (software versions, graphics hardware...) that might be helpful, just ask.

**Comment by LongHairedHacker** [comment] 2022-02-03 20:00
Nope ... unfortunately the glow_example #685 runs into the same error:
```
[sebastian@laptop egui_glow] (master)$ cargo run --example pure
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `/tmp/egui/target/debug/examples/pure`
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
pure: xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

**Comment by LongHairedHacker** [comment] 2022-02-03 22:22
Just for kicks I patched my mesa library using https://bugs.freedesktop.org/attachment.cgi?id=143767 and it actually seems to solve the problem. All examples I tested work now.
So if this is actually a mesa bug creating an error where there should be, is there anything that can be done to work around it on the application side?

**Comment by NiceneNerd** [comment] 2022-03-18 02:05
I can confirm the same issue on Arch under both i3 and Plasma. I tried patching mesa but did not succeed in doing so at all.

**Comment by the-drunk-coder** [comment] 2022-03-21 17:50
Hmm I just updated to egui 0.17.0, using glow instead of glium. Seems like it doesn't happen anymore ? But there's other things that changed in my system configuration as well, so I can't really tell what fixed it.

**Comment by emilk** [comment] 2022-03-22 07:41
Should we perhaps close this in favor of https://github.com/rust-windowing/glutin/issues/1034 ?

**Comment by the-drunk-coder** [comment] 2022-04-17 12:42
Not opposed to that ...

**Comment by emilk** [comment] 2022-04-19 09:52
Closed in favor of https://github.com/rust-windowing/glutin/issues/1034

**Closed by emilk** 2022-04-19 09:52 UTC
Labels: framework, native-winit, native-linux
