### ISSUE TITLE
Dockspace support.

### ISSUE THREAD

**Issue by Jerrody** [emilk/egui#1759] opened 2022-06-22 11:24 UTC
Would be great to have a dockspace like in Imgui.

**Comment by Jerrody** [comment] 2022-06-27 09:48
> docking already has an issue at #655 and a discussion at #424

Cool.

**Comment by emilk** [comment] 2022-07-21 18:49
duplicate of https://github.com/emilk/egui/issues/655

**Closed by emilk** 2022-07-21 18:49 UTC
Labels: feature-request
