### ISSUE TITLE
UI flickering badly on Windows

### ISSUE THREAD

**Issue by crimsondamask** [emilk/egui#838] opened 2021-10-25 00:59 UTC
There is some weird UI flickering when run on Windows. The entire UI looks messy and jagged whenever there is interaction. However, it runs fine on Linux on the same computer. I have experienced the same issue on some old Windows computers (4th Gen and earlier) but not on others that are a bit recent.

**Comment by hamamo** [comment] 2022-01-19 16:15
I'm having the same problem on Windows, with `glium` as well as `glow` backends.
Maybe the problem lies deeper?

**Comment by hamamo** [comment] 2022-03-03 11:06
Apparently this issue was closed somewhere along the line - I pulled https://github.com/emilk/eframe_template/ freshly today and the bug is gone. I don't know yet where it was fixed, though.

**Comment by imxood** [comment] 2022-03-03 13:42
Duplicate of #1315

**Comment by YassinEldeeb** [comment] 2022-03-27 13:52
**Describe the bug**
On windows 7, there's a very weird flickering and images can't be loaded.

**To Reproduce**
Steps to reproduce the behavior:
1. Clone the [project](https://github.com/YassinEldeeb/deadliner/tree/main/gui)
2. Compile for windows via `cargo build --release --target x86_64-pc-windows-msvc` (Install the target first, If you don't have it).
3. Open the executable on Windows 7 from `target/release/deadliner.exe`
4. You'll see this strange behavior that I'm gonna link an image and a video about.

**Expected behavior**
To work on windows 7 just like windows 10.

![app-gui](https://user-images.githubusercontent.com/72823042/160282972-ec7f84f2-13cd-4bfc-909c-d9cfdc6fbf66.png)


**Image and video I got from a user**
![IMG-20220327-WA0013](https://user-images.githubusercontent.com/72823042/160282576-5d284ddc-1abf-4b2e-abac-12190528dfea.jpg)

https://user-images.githubusercontent.com/72823042/160283364-0597617a-ffe3-4f45-864a-ded5dddaebaa.mp4

**Desktop (please complete the following information):**
 - OS: Windows 7
 - CPU: Intel core I5 5th gen
 - RAM: 4GB
 - Eframe Version: 0.17.0
 
**Additional context**
It works perfectly on windows 10, this bug is only reproducible on window 7 even though the hardware on it isn't that bad to be this laggy.

And yes I'm just stunned like you, like..wtf is that, how? 😅

**Comment by YassinEldeeb** [comment] 2022-03-27 14:02
@hamamo the bug isn't resolved yet unfortunately.

**Comment by t18b219k** [comment] 2022-03-28 14:49
maybe linking ANGLE would resolve problem.
if browser egui demo working perfectly.

**Comment by t18b219k** [comment] 2022-03-28 17:34
@YassinEldeeb 
dive deeply into glutin I found a way to enforce glutin to use EGL.
If we request glutin::Api::OpenGlEs to glutin try to use EGL first. but if we give shared wgl context in initialization use WGL.
```rust
pub fn create_display<T>(
    native_options: &NativeOptions,
    wb: WindowBuilder,
    el: &EventLoop<T>,
) -> (
    glutin::WindowedContext<glutin::PossiblyCurrent>,
    egui_glow::glow::Context,
) {
    //in some case glutin use EGL.
    // we use this behaviour.
    // if we Request OpenGLES .first try to use EGL context fallback to WGL ones in windows.

    let cb = {
        let mut cb =glutin::ContextBuilder::new()
        .with_depth_buffer(native_options.depth_buffer)
        .with_multisampling(native_options.multisampling)
        .with_srgb(true)
        .with_stencil_buffer(native_options.stencil_buffer)
        .with_vsync(native_options.vsync);
        cb.gl_attr.version=GlRequest::Specific(Api::OpenGlEs, (3, 0));
        cb
    };
    let gl_window =unsafe {
            cb
            .build_windowed(wb, el)
            .unwrap()
            .make_current()
            .unwrap()
    };
    let gl = unsafe {
        egui_glow::glow::Context::from_loader_function(|s| gl_window.get_proc_address(s))
    };

    (gl_window, gl)
}
```  


but we need to package libEGL.dll,libGLESv2.dll with build artifact.
I built ANGLE by mozangle. and gather dlls by hand and drop it with App works well.
```toml
[dependencies]
mozangle={version="0.3",features=["build_dlls","egl"]}
egui_glow = {git="https://github.com/emilk/egui.git",branch="master"}
glutin = "0.28.0"
```

**Comment by YassinEldeeb** [comment] 2022-03-28 17:37
@t18b219k Wow! Thank you for this, I'll try it out.

**Comment by YassinEldeeb** [comment] 2022-03-28 17:42
I'll try to get access to a windows 7 machine and when I got one I'll let you know about the results, Thanks again!

**Comment by emilk** [comment] 2023-12-29 10:13
Since the glium backend is gone and moved out to a separate repo (https://github.com/fayalalebrun/egui_glium) I'm gonna close this issue

**Closed by emilk** 2023-12-29 10:13 UTC
Labels: bug, eframe, native-glium, egui_glow
