### ISSUE TITLE
Detect mouse events in a `Plot`

### ISSUE THREAD

**Issue by IndianBoy42** [emilk/egui#759] opened 2021-10-02 04:43 UTC
I want to make an interactive plot, so this involves being able to click and drag the various plot elements. Currently you can use the general `Response::clicked_by` etc for detecting clicks/drags anywhere on the whole plot but it has a few drawbacks:

- The positions/deltas we get are in pixels, not plot coordinates.
- We would have to somehow manually check which plot elements were interacted with.

I think it would be nice if adding elements to the plot also gave something like a `Response` object that allows us to check interactions. 
Making things automatically be draggable (especially Points, Polygons) would be nice as well. 
As a long term goal, perhaps we could have projection/closest point methods as well. But first the ability to detect click/drag on Plot elements would be good

I am just starting to learn how to use egui, so apologies if I have missed an existing feature.

**Comment by IndianBoy42** [comment] 2021-10-02 07:45
Related to #734 but more about events

**Comment by jbuckmccready** [comment] 2022-01-15 22:58
@EmbersArc The mouse position functions work great! Related to this interactive/event handling plots I would like to enable/disable [plot dragging to change the bounds](https://docs.rs/egui/latest/egui/widgets/plot/struct.Plot.html#method.allow_drag) based on where in the plot the pointer was pressed (example use case: if certain parts of the plot are editable and a control point is pressed I want to disable dragging to change bounds and instead use the drag to change the plot data). The problem is the [Plot](https://docs.rs/egui/latest/egui/widgets/plot/struct.Plot.html) is consumed in the call to [show](https://docs.rs/egui/latest/egui/widgets/plot/struct.Plot.html#method.show) so I am not sure how to disable dragging based on the pressed plot location. I thought maybe I could just implement dragging plot bounds separately but I couldn't find a way to edit the plot bounds programmatically.

**Comment by emilk** [comment] 2022-04-16 19:47
I think this is closed by the PR:s above

**Closed by emilk** 2022-04-16 19:47 UTC
Labels: feature-request, plot
