### ISSUE TITLE
Make non-editable TextEdit background configurable

### ISSUE THREAD

**Issue by Shatur** [emilk/egui#1466] opened 2022-04-09 08:12 UTC
**Is your feature request related to a problem? Please describe.**
There is no way to change the background of non-editable `TextEdit` using visuals because the background is hard-coded:
https://github.com/emilk/egui/blob/dd58d5175faa9a21eebb45c4a9615c314be51f56/egui/src/widgets/text_edit/builder.rs#L322

**Describe the solution you'd like**
Use values from visuals to let users configure the look.

**Comment by emilk** [comment] 2022-04-09 11:06
I think this can be considered as a duplicate of https://github.com/emilk/egui/issues/1000

**Closed by emilk** 2022-04-09 11:06 UTC
Labels: feature-request

**Comment by Shatur** [comment] 2022-04-09 11:08
> I think this can be considered as a duplicate of https://github.com/emilk/egui/issues/1000

But in #1000 author suggested to change look. But I just suggesting to just background customizable via styles.

**Comment by emilk** [comment] 2022-04-09 11:47
True, but it is a similar discussion - what _should_ be the behavior of immutable TextEdit? Should "selectabel text" be its own widget? etc

**Comment by Shatur** [comment] 2022-04-09 11:55
Yes, I understand your point. Answered in #1000.

If we do decide to leave the `TextEdit` as it is, it would be nice to remove the hard-coded transparent background to let users configure this.
