### ISSUE TITLE
Immediate Viewport speed issue

### ISSUE THREAD

**Issue by rustbasic** [emilk/egui#4022] opened 2024-02-11 10:29 UTC
Viewport speed issue

If you run `Immediate Viewport` while the program is at 60 frames (per second),
it will be at 50 frames.

If you have `two monitors` and the Viewport is on a different screen from the program,
the frame rate will be 30.

Is this a normal reaction?

egui version : ALL
OS : Windows 10

**Comment by rustbasic** [comment] 2024-02-12 11:39
If you have two monitors and the viewport is on a different screen than your program:
The frame rate is 30.

sometimes, In this case the frame rate may be 1. 
And if the same situation occurs even if you restart the program, it may be 30 again.

**Comment by emilk** [comment] 2024-10-23 12:34
* Is this a duplicate of https://github.com/emilk/egui/issues/5249 ?

**Comment by rustbasic** [comment] 2024-10-23 14:56
> * Is this a duplicate of [Speed ​​issues on Windows when `immediate viewport` is on another screen #5249](https://github.com/emilk/egui/issues/5249) ?

It's a duplicate, except for the symptom of `FPS 50` in `glow`. I'll close it for now.

**Closed** 2024-10-23 14:57 UTC
Labels: bug
