### ISSUE TITLE
Unable to ineract with table row widgets (regression)

### ISSUE THREAD

**Issue by wesley-ducharme-haven** [emilk/egui#4047] opened 2024-02-14 20:01 UTC
# Unable to interact with table row widgets

**I tested with 0.26.2 and also latest master as of (14/02/2024).**

0.26 introduced a regression to the  `TableBuilder` / `Table` behavior. 

`TableBuilder::new(ui).sense(Sense::click(())`
**Previous:** Rows are clickable. Inner widgets can be interacted with (for example a checkbox)
**Current:** Rows are clickable. Inner widgets *can't be interacted with*.

You need to remove `.sense(Sense::click())` to have the inner widgets be interactable.

## Reproduce

You can reproduce this behavior using the [web demo](https://www.egui.rs/).

1. Enable "Table Demo" on the right side
2. Enable "Clickable rows"
3. Rows are clickable
4. Try to use the "Click me" checkbox, it doesn't work.
5. Disable "Clickable rows"
6. Rows aren't clickable
7. Try to use the "Click me" checkbox, it works

**Comment by emilk** [comment] 2024-02-17 10:48
The problem is that `StripLayout::add` does the cell interaction _on top_ of the contents, but it needs to be done below it (before adding contents). 🤔

**Comment by emilk** [comment] 2024-02-18 11:25
I closed this by accident. I have a rough plan for this, and will hopefully find time to work on in the coming week

**Closed** 2024-02-20 13:50 UTC
Labels: bug
