### ISSUE TITLE
[regression] [eframe] Backspace and arrow keys don't work in `TextEdit`

### ISSUE THREAD

**Issue by crumblingstatue** [emilk/egui#5181] opened 2024-09-28 09:28 UTC
On Linux, X11, pressing backspace or using the arrow keys to move the cursor have no effect.
This is a regression, because it used to work in 0.28.

**Desktop:**
 - OS: Linux, X11

**Additional context**
#4912 is the pull request that introduces the regression.

**Comment by crumblingstatue** [comment] 2024-09-28 09:31
Ah, this looks like it might be a duplicate of #5008.
I'm surprised egui 0.28 was released with such a serious regression.

**Comment by emilk** [comment] 2024-09-30 06:49
Closed as duplicate of https://github.com/emilk/egui/issues/5008

**Closed by emilk** 2024-09-30 06:49 UTC
Labels: bug
