### ISSUE TITLE
[CRASH] Zooming out too far crashes web demo

### ISSUE THREAD

**Issue by ngortheone** [emilk/egui#3685] opened 2023-12-06 00:39 UTC
In demo app go to plot -> custom axes and zoom out a lot.

![2023-12-05-163418](https://github.com/emilk/egui/assets/18271144/cfd9b10b-0197-4818-9473-4e890f5f4d6c)

This reliably crashes both the webdemo and the desktop version running in eframe
No meaningful error message is produced after the crash

**Comment by emilk** [comment] 2023-12-28 08:22
Duplicate of https://github.com/emilk/egui/issues/3462

**Closed by emilk** 2023-12-28 08:22 UTC
Labels: bug
