### ISSUE TITLE
Window corner rescale cursor has wrong orientation

### ISSUE THREAD

**Issue by EmbersArc** [emilk/egui#332] opened 2021-04-22 17:02 UTC
**Describe the bug**
When I place the cursor in any corner of a window that can be resized, it points in the wrong direction.
![image](https://user-images.githubusercontent.com/1352472/115754909-fe345400-a39c-11eb-9229-d4b1fc37ff89.png)

**Expected behavior**
(edited the code a bit)
![image](https://user-images.githubusercontent.com/1352472/115754827-e78dfd00-a39c-11eb-8234-fdbb6710b7e1.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux KDE

Does anyone know if this is an issue on other OSs or desktop environments as well?

**Comment by emilk** [comment] 2021-04-22 17:53
Can't reproduce on my mac.

Does this happen if you check out this repo and run `cargo run`? If so it is probably a bug in [winit](https://github.com/rust-windowing/winit).

If you are using some third-party egui integration, the bug is probably there.

**Comment by EmbersArc** [comment] 2021-04-22 18:52
Yes, this is on a clean clone of the master branch with `cargo run`. I reported the issue in the winit repo.

**Comment by emilk** [comment] 2021-05-09 12:14
Closed in favor of https://github.com/rust-windowing/winit/issues/1912

**Closed by emilk** 2021-05-09 12:14 UTC
Labels: bug
