### ISSUE TITLE
Items are not clickable when inside a row of a `TableBuilder`

### ISSUE THREAD

**Issue by AmesingFlank** [emilk/egui#4064] opened 2024-02-18 04:58 UTC
I noticed that items inside rows of a `TableBuilder` are no longer clickable. This can be reproduced in one of the demos in https://www.egui.rs/#demo

See this video for example:

https://github.com/emilk/egui/assets/16066115/994f72d4-a6f2-4a49-9784-3c1f4c302780

This checkbox within the table row is not being checked when clicked.

**Comment by YgorSouza** [comment] 2024-02-18 08:19
This was first reported in #4047, which was closed apparently by mistake since the issue is not resolved yet.

**Comment by emilk** [comment] 2024-02-18 11:25
Oops! I re-opened https://github.com/emilk/egui/issues/4047, and I'll close this as a duplicate.

**Closed by emilk** 2024-02-18 11:25 UTC
Labels: bug
