### ISSUE TITLE
no way to open context menus on touchscreens

### ISSUE THREAD

**Issue by amomentunfolding** [emilk/egui#3444] opened 2023-10-07 16:00 UTC
**Describe the bug**

When using context_menu it seems to be only accessible by secondary click and can therefore not be opened on a touch screen device.

**To Reproduce**
1. Try to open a context menu on a touch screen
2. Realize there is no way

**Expected behavior**

A reasonable default I feel would be to have it open on a long press.

I reckon it would be somewhat straightforard to implement with `egui::PointerState::press_start_time` - at least that's what I will do for a workaround in my project, but perhaps it should be part of the API as well.

**Smartphone (please complete the following information):**
 - Device:   Xiaomi Redmi Pad
 - OS:  Android 13
 - Browser:  Chrome Beta / also tried Firefox.
 - Version:  Latest

**Comment by amomentunfolding** [comment] 2023-10-09 11:03
for anyone dealing with the same issue, i wrote this workaround:

```rust
use egui::{
    Ui,
    Response
};
// cannot be longer than .7~ seconds because after that Response.hovered() returns false
// probably it could be longer by using pointer_pos check instead of hovered() but .4s is a good speed so w/e
const LONG_PRESS_TIME: f64 = 0.4;

pub trait TouchEnabledContextMenu {
    fn context_menu_touch_enabled(self, ui: &mut Ui, add_contents: impl FnOnce(&mut Ui)) -> Self;
}

impl TouchEnabledContextMenu for Response {
    fn context_menu_touch_enabled(self, ui: &mut Ui, add_contents: impl FnOnce(&mut Ui)) -> Self {
        let popup_id = ui.make_persistent_id(self.id.with("context_touch_menu"));
        let is_open = ui.memory(|mem| mem.is_popup_open(popup_id));
        let mut should_open = false;

        if self.secondary_clicked() {
            should_open = true
        } else if self.hovered() && !is_open {
            ui.input(|i| {
                if let Some(pst) = i.pointer.press_start_time() {
                    if (i.time - pst) > LONG_PRESS_TIME {
                        should_open = true
                    }
                }
            });
        };

        if should_open {
            ui.memory_mut(|mem| mem.toggle_popup(popup_id));
        }

        egui::popup::popup_above_or_below_widget(
            ui,
            popup_id,
            &self,
            egui::AboveOrBelow::Above,
            |ui| {
                ui.set_min_width(120.0);  // popup is extremely thin without this, regardless of contents
                add_contents(ui);
            }
        );

        self
    }
}
```

**Comment by abey79** [comment] 2024-02-16 11:37
This might be a duplicate of #865, but best kept open for the useful workaround.

**Closed** 2024-03-20 10:49 UTC
Labels: bug
