### ISSUE TITLE
Visible jitter when the window size changes

### ISSUE THREAD

**Issue by sbfkcel** [emilk/egui#1930] opened 2022-08-18 06:03 UTC
macOS Monterey 12.5.1
Apple M2

Demo
https://user-images.githubusercontent.com/5469785/185305567-e5b9b8e2-f35f-4836-8848-987c611b5e42.mov

**Comment by emilk** [comment] 2022-08-18 07:02
I fail to play your video. Assuming you are talking about the native eframe window, this sounds like a duplicate of https://github.com/emilk/egui/issues/903

Let me know if it isn't

**Closed by emilk** 2022-08-18 07:02 UTC
Labels: bug

**Comment by sbfkcel** [comment] 2022-08-18 07:21
Yes, same problem. I tested other rust ui frameworks and it works fine.
