### ISSUE TITLE
Clipping issue with resizable windows at max size

### ISSUE THREAD

**Issue by apessino** [emilk/egui#883] opened 2021-11-06 19:01 UTC
Hello!

This seems like a potentially unintended behavior with window resizing. I took a quick video showing the issue:

https://user-images.githubusercontent.com/8810462/140620577-051d032c-0235-4111-9bc7-fc3e3b89979d.mp4

It appears that the clipping area of the parent window is affected even if the window is not visibly resized. Regardless of the problem with the combo box this does not seem like an intended side effect of resizing.

Notice that in this case the problem is easily corrected by setting the window to not resizable, but since resizing is the default window setting and it is an issue with resizable windows that are at max size, then it should probably be investigated at some point.

Thanks!

A=

**Comment by emilk** [comment] 2021-11-07 18:24
Duplicate of https://github.com/emilk/egui/issues/825

**Closed by emilk** 2021-11-07 18:24 UTC
Labels: bug, duplicate

**Comment by apessino** [comment] 2021-11-07 18:42
I did see that issue and it seemed like a different problem to me. In the case I was showing the drop down is not clipping unless you "resize" the window. Why is the parent clip rect changing if the window is not actually resized? It seems like a different and suspicious behavior to me. Then again, you know best and if you think it's all the same then OK. :)

Also, perhaps the window should not register as resizable to the user (edge highlighting/pointer change) unless there is an actual range for the window to resize to.

**Comment by emilk** [comment] 2021-11-07 20:11
Each resizable window has a desired size, which it may or may not fill. This occasionally creates some weird behavior, but it is a difficult problem to solve in immediate mode.

>  perhaps the window should not register as resizable to the user (edge highlighting/pointer change) unless there is an actual range for the window to resize to.

How can the window know whether or not there was a widget in it that respected the size preferences of the window? Again, limitations of immediate mode. So as a user you have to manually specify if your window should be resizable or not.

**Comment by apessino** [comment] 2021-11-07 21:44
Fair point, it's easy to forget that you have minimal cached information to make sizing/interaction decisions. I guess the only way to keep everything automatic while avoiding artifacts would be to split processing into a layout and then a process/render pass, as you have mentioned before.

In the meantime managing the resizable flag on my end makes sense and it's easy to do - thanks!

A=
