### ISSUE TITLE
SVG images are blurry when `ctx.pixel_per_point` is not equal to 1.0

### ISSUE THREAD

**Issue by Umatriz** [emilk/egui#4808] opened 2024-07-09 05:43 UTC
**Describe the bug**

**To Reproduce**
1. Add a SVG image to your app using `Image::new`
2. Set `ctx.pixels_per_point` to something that is not equal to 1.0 (1.5 for example)
3. See that image now blurry

**Expected behavior**

Image must be scaled but still be sharp.

**Screenshots**

This is an incon with `ctx.pixels_per_point = 1.5`
![ppp1.5](https://github.com/emilk/egui/assets/102140917/97f52a6b-4c7c-480b-83ed-0bffe6734d92)

The same Icon with `ctx.pixels_per_point = 1.0`. Yes it's shap and the same sharpness can be achived on the higher `pixel_per_point` by adding `.fit_to_original_size(1.0 / ui.ctx().pixels_per_point())` to the image. But it will keep the image, as it stands, in it's original size so it cannot be considered to be a fix.
![ppp1.0](https://github.com/emilk/egui/assets/102140917/5efd4150-61cb-4925-b1b7-8a3c29a19881)

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser did not test in browser
 - Version 0.28.0

**Additional context**

**Comment by emilk** [comment] 2024-07-09 06:15
Duplicate of https://github.com/emilk/egui/issues/3453

**Closed by emilk** 2024-07-09 06:15 UTC
Labels: bug
