### ISSUE TITLE
show_viewport_immediate's  option transparent is not work

### ISSUE THREAD

**Issue by liaoliao666** [emilk/egui#5264] opened 2024-10-14 17:07 UTC
here is the minimal example

```rust
impl eframe::App for App {
    fn clear_color(&self, _visuals: &egui::Visuals) -> [f32; 4] {
        egui::Rgba::TRANSPARENT.to_array()
    }
   
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) { 
       ctx.show_viewport_immediate(
            egui::ViewportId::from_hash_of("immediate_viewport"),
            egui::ViewportBuilder {
                inner_size: Some(vec2(220.0, 100.0)),
                max_inner_size: Some(vec2(220.0, 100.0)),
                min_inner_size: Some(vec2(220.0, 100.0)),
                resizable: Some(false),
                minimize_button: Some(false),
                maximize_button: Some(false),
                ..Default::default()
            }
            .with_decorations(false)
            .with_transparent(true)
            .with_always_on_top(),
            |ctx, class| {
                assert!(
                    class == egui::ViewportClass::Immediate,
                    "This egui backend doesn't support multiple viewports"
                );

                CentralPanel::default()
                    .frame(egui::Frame::none())
                    .show(ctx, |ui| {
                    
                 });
    }
}
```

**Comment by emilk** [comment] 2024-10-23 12:32
Probably a duplicate of https://github.com/emilk/egui/issues/4451

**Closed by emilk** 2024-10-23 12:32 UTC
