### ISSUE TITLE
auto_bounds is incorrect when plotting a constant (horizontal) line

### ISSUE THREAD

**Issue by bonsairobo** [emilk/egui#3970] opened 2024-02-04 23:38 UTC
**Describe the bug**

When plotting a `Line` whose Y values are all the same (a horizontal line), the plot bounds will always be centered at Y=0, leaving the line out of bounds.

**To Reproduce**

Run this code:

```rust
let line = Line::new(PlotPoints::from_ys_f64(&[2.0, 2.0]));
egui_plot::Plot::new("repro")
    .auto_bounds(true.into())
    .view_aspect(2.0)
    .show(ui, |plot_ui| plot_ui.line(line));
```

**Expected behavior**

The line should be visible.

**Screenshots**

![screen3](https://github.com/emilk/egui/assets/3229981/a3eb0834-0b71-44f8-af45-854efe6bc97c)

OS: Linux
Version: 6.1.69

**Additional Context**

Even adding a single point to the line that isn't equal to the rest will cause the auto-bounds behavior to correctly focus on the line.

**Comment by emilk** [comment] 2024-02-05 08:20
Duplicate of https://github.com/emilk/egui/issues/2307

**Closed by emilk** 2024-02-05 08:20 UTC
Labels: bug
