### ISSUE TITLE
`scroll_with_delta` doesn't work

### ISSUE THREAD

**Issue by marcin-serwin** [emilk/egui#2783] opened 2023-03-04 21:04 UTC
**Describe the bug**

`scroll_with_delta` doesn't seem to work.

**To Reproduce**

1. Create an app with `eframe`.
2. Copy the `scroll_with_delta` example from documentation.
3. Click `Scroll down` button.
4. See that nothing happens.

```rust
use eframe::egui::{self, Vec2};

fn main() -> Result<(), eframe::Error> {
    eframe::run_native(
        "My egui App",
        eframe::NativeOptions::default(),
        Box::new(|_cc| Box::new(MyApp {})),
    )
}

struct MyApp {}

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            let mut scroll_delta = Vec2::ZERO;
            if ui.button("Scroll down").clicked() {
                scroll_delta.y -= 64.0; // move content up
            }
            egui::ScrollArea::vertical().show(ui, |ui| {
                ui.scroll_with_delta(scroll_delta);
                for i in 0..1000 {
                    ui.label(format!("Item {}", i));
                }
            });
        });
    }
}
```

**Expected behavior**

Content scrolls down.

**Screenshots**

[video](https://user-images.githubusercontent.com/12128106/222928092-28c4f85e-29e7-4b11-9992-f4811a4c41ad.webm)

**Desktop (please complete the following information):**

 - OS: GNU/Linux

**Comment by YgorSouza** [comment] 2023-03-04 22:23
It looks like this is the code that handles the `scroll_delta`:

https://github.com/emilk/egui/blob/f94187ab718e8513084e591fcef73356a4971d6b/crates/egui/src/containers/scroll_area.rs#L700-L716

It only takes the delta into account if the pointer is inside the scroll area, so the example will never work, since you have to click a button that is outside the area. If I remove this condition, it works as intended. I don't know why it is written this way, and both the code above and the `scroll_with_delta` method are untouched for almost a year. I also tested with the commit that originally introduced the method (676ff047e9c), and it didn't work there either. If there is no other reason for the `&& ui.rect_contains_pointer(outer_rect)` condition, I supposed it could just be removed and the method will be fixed. But I'll wait to see if anyone has anything to say about it, and do some tests to see if it breaks anything else.

I suspect that since the `scroll_delta` is set in the Context, and is therefore global to the whole UI, the idea is that if there is more than one scroll area, the one that is hovered by the mouse would be the one to use the delta. But I guess if you set it from within the show() method of the scroll area that you want to manipulate, that will not be a problem. But I'm not sure I fully understand how this is supposed to work.

**Closed** 2024-05-28 07:21 UTC
Labels: bug
