### ISSUE TITLE
Can egui have a tab widget?

### ISSUE THREAD

**Issue by lucasjinreal** [emilk/egui#2607] opened 2023-01-19 01:28 UTC
A tab is essentially like this:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/21303438/213334142-bbb9e17f-91e7-4a3b-b71e-4e8ae338d0fa.png">

Or in a older style, which just for switch different pages inside a single page space

**Comment by coderedart** [comment] 2023-01-19 07:04
yes.
just have a look through https://egui.rs demo. it already shows most of the capabilities of egui. and it will also answer your question faster, compared to making an issue.
![image](https://user-images.githubusercontent.com/24411704/213376340-21c87cbe-61f8-444c-9cdd-b5a7c1c231ca.png)

you can use tabs by horizontal collection of selectable label widgets. in the above plot window, the series of "tabs" named Lines, Markers, Legends etc.. are created using https://github.com/emilk/egui/blob/master/crates/egui_demo_lib/src/demo/plot_demo.rs#L81

**Comment by jinfagang** [comment] 2023-01-19 10:25
@coderedart hello, how to make these element center in horizontal? 

```rust
ui.horizontal(|ui| {
                ui.with_layout(egui::Layout::left_to_right(egui::Align::Center), |ui| {
                    ui.selectable_value(&mut self.crt_tool, ToolType::Blank, "Blank");
                    ui.selectable_value(&mut self.crt_tool, ToolType::FBXParse, "FBX Parser");
                });
            });
```

not work

**Comment by jinfagang** [comment] 2023-01-19 10:26
@coderedart hello, how to make these element center in horizontal? 

```rust
ui.horizontal(|ui| {
                ui.with_layout(egui::Layout::left_to_right(egui::Align::Center), |ui| {
                    ui.selectable_value(&mut self.crt_tool, ToolType::Blank, "Blank");
                    ui.selectable_value(&mut self.crt_tool, ToolType::FBXParse, "FBX Parser");
                });
            });
```

not work

**Comment by emilk** [comment] 2024-01-06 22:23
Duplicate of https://github.com/emilk/egui/issues/1624

**Closed by emilk** 2024-01-06 22:23 UTC
Labels: feature
