### ISSUE TITLE
App window is brought to foreground whenever `Context::request_repaint` is called

### ISSUE THREAD

**Issue by Barugon** [emilk/egui#3620] opened 2023-11-24 07:09 UTC
egui version 0.24.0

**Describe the bug**
In addition to what the title says, even without calling `Context::request_repaint`, the window remains on top when I switch to another app.

**To Reproduce**
1. Build and runt the attached project. It will issue a `Context::request_repaint` every second.
2. Switch to another app and note that this app's window will be moved to the foreground.

Even if `Context::request_repaint` is not deliberately called, moving your mouse over any exposed part of the window will bring it to the front.

**Expected behavior**
`Context::request_repaint` should not effect the desktop window order.

**Desktop**
- Memory:                        32.0 GiB
- Processor:                     AMD Ryzen™ 9 3900X × 24
- Graphics:                       AMD Radeon™ RX 6700 XT
- OS Name:                      Fedora Linux 39 (Workstation Edition)
- OS Type:                        64-bit
- GNOME Version:           45.1
- Windowing System:       Wayland
- Kernel Version:              Linux 6.5.12-300.fc39.x86_64

[testy.zip](https://github.com/emilk/egui/files/13456054/testy.zip)

**Comment by emilk** [comment] 2023-11-24 09:16
Thanks for the report!

Is this a new bug for 0.24?

I cannot reproduce on Mac, so I suspect this is a bug specific to Linux/Wayland.

**Comment by sourcebox** [comment] 2023-11-24 16:15
I can confirm that this bug is new in 0.24 and happens also on Linux without using Wayland. I use  `Context::request_repaint_after` in my application.

**Comment by Barugon** [comment] 2023-11-24 21:07
> Is this a new bug for 0.24?

Yes.

> Does it still happen if you use the `"wgpu"` feature of `eframe`?

If I try to build with the `"wgpu"` feature then I get this error:
```
the package `wgpu` depends on `web-sys`, with features: `GpuComputePassTimestampWrite` but `web-sys` does not have these features.
```

**Comment by RegenJacob** [comment] 2023-11-25 13:16
I tested it with the wgpu feature enabled and the issue still exist

**Comment by emilk** [comment] 2023-11-27 06:58
> > Does it still happen if you use the `"wgpu"` feature of `eframe`?
> 
> If I try to build with the `"wgpu"` feature then I get this error:
> 
> ```
> the package `wgpu` depends on `web-sys`, with features: `GpuComputePassTimestampWrite` but `web-sys` does not have these features.
> ```
> 
> [edit] I don't know why `web-sys` needs to be pulled in for a non-wasm project.

Very weird, but should be fixed with `RUSTFLAGS='--cfg=web_sys_unstable_apis'`

**Comment by ItsEthra** [comment] 2023-11-27 14:49
Can't reproduce on hyprland after applying fix for #3628, this might be a duplicate. Could you try disabling x11 feature and trying again?

**Comment by emilk** [comment] 2023-11-27 16:26
Potential fix: https://github.com/emilk/egui/pull/3643

**Comment by Barugon** [comment] 2023-11-27 17:07
#3643 fixes the issue for me.

**Closed** 2023-11-27 17:16 UTC
Labels: bug, eframe, native-linux
