### ISSUE TITLE
[Web Demo] Blurry rendering when browser window has odd width / height

### ISSUE THREAD

**Issue by daniel5151** [emilk/egui#103] opened 2021-01-08 17:56 UTC
Consider this side-by-side comparison of the basic demo pane:

![egui-crisp](https://user-images.githubusercontent.com/2389445/104047741-23b39e00-51b0-11eb-8b65-d813f7bfad38.png) ![egui-blurry](https://user-images.githubusercontent.com/2389445/104047742-24e4cb00-51b0-11eb-8864-15ab3ec5c2c8.png)

The left screenshot was taken in a browser window with dimensions 1000px x 1200px, while the one on the right was taken in a browser window with dimensions 1001px x 1200px. i.e: a difference of one pixel resulted in the entire image becoming significantly blurrier.

A similar issue occurs when the window's height is odd, albeit to a lesser extent.

Tested in Google Chrome Version 87.0.4280.88 on Ubuntu 20.10 with NVIDIA Drivers

**Comment by emilk** [comment] 2021-01-11 14:31
Good find - I can reproduce in Firefox on Mac too. Maybe a simple fix is to just round down the canvas size to the nearest multiple-of-2.

**Comment by emilk** [comment] 2021-01-17 10:29
I was gonna fix this now, but can no longer reproduce it. Weird :/

**Comment by bugadani** [comment] 2021-01-17 17:12
I can :)
![image](https://user-images.githubusercontent.com/977627/104850459-8400b900-58ef-11eb-9c86-b650d54ee8e3.png)
MS Edge,  version 87.0.664.75

**Comment by emilk** [comment] 2021-01-24 11:48
Anyone want to take a stab at this? I can't reproduce on my machine, so I can't.

I'm guessing we need to add some rounding in https://github.com/emilk/egui/blob/master/egui_web/src/lib.rs#L117:L141

My theory is that we need to round (or rather `floor`) the height and width to the next factor-of-2 in pixel or in point size. Or maybe just round to the nearest integers.

**Comment by bugadani** [comment] 2021-01-24 13:55
Well for me (at least on firefox, which I don't use, LOL) was to turn off webgl antialiasing in about:config. The option is not available in Edge (chromium) though, so this is only food for thought. Also, my head hurts from staring into blurry text :)

On
![image](https://user-images.githubusercontent.com/977627/105632544-f6274f80-5e53-11eb-9a40-53e7cd9cde0d.png)

Off
![image](https://user-images.githubusercontent.com/977627/105632533-e3ad1600-5e53-11eb-8409-384863ad09f3.png)

**Comment by crumblingstatue** [comment] 2021-01-31 19:27
I can reproduce this on chromium 88, and I can confirm it only happens on odd width/height. Unfortunately the height is odd when my browser is maximized. If anyone wants me to test something, let me know.

**Comment by aakamenov** [comment] 2021-01-31 19:34
I've submitted a PR for this - #149 . Managed to reproduce and fix on Edge and Opera (both Chromium), but should be fixed on other browsers. If anyone was getting this on Firefox or Chrome, would be nice to confirm that it doesn't occur anymore.

**Closed** 2021-02-01 19:44 UTC
Labels: bug, good first issue, help wanted, web
