### ISSUE TITLE
Problem locating rusttype

### ISSUE THREAD

**Issue by Chafalleiro** [emilk/egui#184] opened 2021-02-19 02:05 UTC
Hi:
I'm totally new in rust so maybe I installed something incorrectly. When checking the examples for some reason I got an error with rusttype, cargo said:
error: no matching package named `rusttype` found
location searched: https://github.com/rust-lang-nursery/rand
required by package `epaint v0.9.0 (C:\Users\chafalleiro\rust\egui\epaint)`
Finally I added to the Cargo.toml file in the epaint dir:
rusttype = { git = "https://gitlab.redox-os.org/redox-os/rusttype" }
and it worked.

**Comment by emilk** [comment] 2021-02-20 11:16
Sounds like a networks issue or a misconfigured cargo or something. I'm gonna close this since there aren't any steps to reproduce, and seems to not at all be related to the egui/epaint crates.

**Closed by emilk** 2021-02-20 11:16 UTC
