### ISSUE TITLE
epi::App::save() is not called on shutdown

### ISSUE THREAD

**Issue by nbigaouette** [emilk/egui#597] opened 2021-07-31 16:02 UTC
Upgrading my app to egui 0.13.1, I found out my app state is not reloaded when restarted.

I checked the template repo (https://github.com/emilk/egui_template/blob/master/src/app.rs#L44-L47) to see if the `save()` function is called there (needs the `--features persistence` flag) and it's not called either.

Could it be a bug in egui?

Thanks!

**Comment by emilk** [comment] 2021-08-15 15:20
It *should* be called at https://github.com/emilk/egui/blob/master/egui_glium/src/backend.rs#L352

What OS are you on? Can you attach a debugger and see what happens? Maybe `glutin::event::Event::LoopDestroyed` isn't sent?

**Comment by emilk** [comment] 2021-08-15 18:26
I can reproduce this on Mac, but only if I press cmd-Q. It seems winit does not send a `LoopDestroyed` event when I do that 😭.

**Comment by nbigaouette** [comment] 2021-09-04 15:02
Thanks for looking into this and sorry for my late reply.

I see the same behaviour you are describing with egui 0.14.1.

It's unfortunate that the problem might be in winit...

**Comment by FredericaBernkastel** [comment] 2021-09-04 18:20
Same on Windows 7 x64 / egui 0.14.2.

**Comment by TimonPost** [comment] 2021-09-22 17:40
System interruption events are likely not being monitored by Winit. One way you might want to tackle this is by implementing a signal handler yourself and call save if it triggers. https://rust-cli.github.io/book/in-depth/signals.html.

**Comment by TimonPost** [comment] 2021-09-22 17:57
Maybe a workaround: implement a signal handler yourself and call `epi::App::save() ` if it triggers. https://rust-cli.github.io/book/in-depth/signals.html.

**Comment by emilk** [comment] 2021-09-22 19:23
To clarify: it used to be the case that when, on Mac, I had an eframe window in focus and pressed Cmd-Q it would get the `Event::LoopDestroyed` and save the state. Now it no longer receives that message.

Adding a signal handler to egui_glium seems like a very good idea. Any takers? I guess we we would need to wrap the app state in a `Arc<Mutex<Box<App>>>` so it can be shared with the signal handler.

**Comment by TimonPost** [comment] 2021-09-22 20:53
There are a couple of ways to do it.
1. Using a separate thread for that system and events. And then communicate those events via a channel to the app state. [[1]](https://rust-cli.github.io/book/in-depth/signals.html#using-channels)
2. Let the user handle the signals, and save the file.
3. There might be an option to just poll for those signals using the signal-hook create. I have done this before using mio, however, this is likely not a dependency you want to include. This would allow you to poll for events in the ui-loop. [[2]](https://github.com/vorner/signal-hook/tree/master/signal-hook-mio)
4. Passing the entire app wrapped into an arc mutex to the signal thread. 

I think the channels are most clean, we could just use the standard library channels, since its just one way (event thread -> app). It would have the overhead of an extra thread. Tho the thread will not heave much overhead, and will just block waiting for the next system event. There doesn't seem to be a way around the thread other than using a library like mio.

**Comment by nyvs** [comment] 2021-11-05 02:41
I tried debugging a bit. For me `Persistence.from_app_name.create_storage` comes back with None apparently, which leads .save to not being able to save. It's weird that I dont see the `FileStorage::from_app_name`'s `eprintln!` tho. I have to investigate further...

**Comment by emilk** [comment] 2022-01-17 13:21
I'll close this and defer to the winit bug:

* https://github.com/rust-windowing/winit/issues/1998

**Closed by emilk** 2022-01-17 13:21 UTC
Labels: bug, native-winit
