### ISSUE TITLE
Monospace font rendering is fuzzy for me

### ISSUE THREAD

**Issue by anderspitman** [emilk/egui#109] opened 2021-01-12 13:33 UTC
First off all, very impressive work. The web demo runs very smooth on my devices.

While most of the UI text renders nice and crisp, the monospace stuff is quite fuzzy. Is this a known issue/quick fix, or maybe something specific to my system (Linux 5.10/Chromium 87)?

**Comment by emilk** [comment] 2021-01-12 13:40
Could it be a duplicate of https://github.com/emilk/egui/issues/103?

If not, could it be you have zoomed your browser page? What is your scale factor? It can be found in the "inspection" window under "input" (number of physical pixels per logical point).

**Comment by emilk** [comment] 2021-01-26 20:33
Closed as suspected duplicate

**Closed by emilk** 2021-01-26 20:33 UTC
