### ISSUE TITLE
Android WASM google keyboard backspace not working with suggestions

### ISSUE THREAD

**Issue by v-kat** [emilk/egui#4403] opened 2024-04-24 20:17 UTC
The eframe text_agent based WASM keyboard on Android seems to be having issues with suggestions and swallowing backspace to only get rid of text in the suggestions and not the actual input. I dunno if this is related to how egui is dispatching events and/or some android keyboard API quirks. I replicated the problem on multiple Android browsers including Firefox and Chromium based ones and didn't see it on the latest version of iOS.

![wasm_keyboard](https://github.com/emilk/egui/assets/1297926/3665cc5e-c757-4114-9615-62f50e593989)
 ^ the Shhhh gets deleted and no text from the input is modified until the suggestion disappears.

**To Reproduce**
1. Go to www.egui.rs on android with a web browser
2. Select the Widget Gallery and click the TextEdit
3. Enter some text and get some Google keyboard suggestions
4. Use the lower-right backspace key and notice that the text edit isn't modified until the suggestions disappear

**Expected behavior**
The text edit contents are immediately editable without having to get rid of the suggestions 

**Smartphone:**
 - Device: OnePlus Nord
 - OS: Android 12
 - Browser: Firefox, Brave
 - Version: latest

**Comment by mvlabat** [comment] 2024-07-07 07:58
Hi! Apologies for neglecting this PR for so long. I've just tested it on my Android: for some reason, the keyboard disappears immediately after opening it. It seems like there's another click/touch event that follows immediately after that causes this behaviour.

**Comment by emilk** [comment] 2024-07-15 08:47
I think this is a duplicate of
* https://github.com/emilk/egui/issues/1121

Part of:
* https://github.com/emilk/egui/issues/4500

**Closed by emilk** 2024-07-15 08:47 UTC
Labels: bug
